services:
  postgres:
    image: postgres:16-alpine
    container_name: srtroney-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: srtroney
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - srtroney-postgres-data:/var/lib/postgresql/data

volumes:
  srtroney-postgres-data: