[build]
  command = "prisma generate && npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CRM_ADMIN_USERNAME,CRM_ADMIN_PASSWORD,AUTH_SECRET,DATABASE_URL"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**"
