export type Discipline = {
  slug: string;
  label: string;
  eyebrow: string;
  summary: string;
  accent: string;
  projects: { title: string; description: string; result: string }[];
};

export const disciplines: Discipline[] = [
  { slug: "graphic-design", label: "Graphic Design", eyebrow: "01 / Visual systems", summary: "Clear visual communication for campaigns, products, and ideas that need to land quickly.", accent: "orange", projects: [{ title: "Editorial campaign system", description: "A flexible visual language for a multi-channel launch.", result: "12 reusable layouts" }, { title: "Product launch toolkit", description: "Social, print, and presentation assets from one compact system.", result: "One source of truth" }, { title: "Signal posters", description: "High-contrast posters designed to make technical ideas feel human.", result: "Built for attention" }] },
  { slug: "branding", label: "Branding", eyebrow: "02 / Identity", summary: "Positioning, identity, and visual direction for businesses finding a sharper voice.", accent: "yellow", projects: [{ title: "Founder-led identity", description: "A practical identity system built around a distinctive point of view.", result: "Voice before decoration" }, { title: "Local retail refresh", description: "A warmer, clearer brand system for a growing retail business.", result: "Sharper shelf presence" }, { title: "Naming and direction", description: "A foundation for a product that needed to be understood fast.", result: "Clarity at first glance" }] },
  { slug: "photography", label: "Photography", eyebrow: "03 / Still image", summary: "Product, portrait, and commercial photography built around light, texture, and intent.", accent: "cyan", projects: [{ title: "Product lighting studies", description: "Turning basic fixtures into a consistent commercial look.", result: "Light over gear" }, { title: "Founder portrait series", description: "Portraits that feel capable, direct, and unperformed.", result: "Human, not polished" }, { title: "Material archive", description: "Close studies of products, surfaces, and the details people remember.", result: "Texture as evidence" }] },
  { slug: "videography", label: "Videography", eyebrow: "04 / Moving image", summary: "Commercial and documentary video from first idea through final graded master.", accent: "red", projects: [{ title: "Commercial product film", description: "A concise visual story designed to make a product feel tangible.", result: "Story before specs" }, { title: "Field investigation", description: "On-location research shaped into a useful short documentary.", result: "Reality on camera" }, { title: "Founder profile", description: "A structured conversation turned into a credible story.", result: "Trust in motion" }] },
  { slug: "motion-graphics", label: "Motion Graphics", eyebrow: "05 / Motion system", summary: "Kinetic type, explainers, and visual rhythm for ideas that need movement.", accent: "pink", projects: [{ title: "Kinetic type package", description: "A repeatable motion language for short-form dispatches.", result: "Faster story beats" }, { title: "Product explainer", description: "A complex workflow reduced to a clear animated sequence.", result: "Less cognitive load" }, { title: "Campaign transitions", description: "Motion details that made a static campaign feel alive.", result: "A moving identity" }] },
  { slug: "web-development", label: "Web Development", eyebrow: "06 / Digital products", summary: "Fast, accessible websites and tools that turn a good proposition into a useful experience.", accent: "cyan", projects: [{ title: "Real estate intake pipeline", description: "Connected forms, webhooks, CRM, and SMS into one faster workflow.", result: "+340% speed to lead" }, { title: "Training gym web app", description: "Rebuilt booking and membership flows for mobile-first conversion.", result: "+45% bookings" }, { title: "Operations dashboard", description: "A focused internal tool for seeing the work that matters.", result: "Less spreadsheet friction" }] },
  { slug: "ecommerce", label: "E-commerce", eyebrow: "07 / Commerce", summary: "Storefronts, product pages, and experiments grounded in unit economics and customer behavior.", accent: "yellow", projects: [{ title: "Desk gear DTC store", description: "Focused product positioning, UGC creative, and paid testing.", result: "2.8 blended ROAS" }, { title: "Checkout friction audit", description: "Found the points where intent disappeared before payment.", result: "Fewer dead ends" }, { title: "Offer architecture", description: "Reframed a catalog around one clearer customer promise.", result: "Product before clutter" }] },
  { slug: "advertisements", label: "Advertisements", eyebrow: "08 / Paid attention", summary: "Creative testing and campaign systems designed around a measurable next action.", accent: "orange", projects: [{ title: "Meta creative sprint", description: "A disciplined test of hooks, offers, and audience signals.", result: "Creative over guesswork" }, { title: "TikTok UGC system", description: "A repeatable process for producing and comparing short-form ads.", result: "More shots on goal" }, { title: "Landing page variants", description: "Message and layout tests built around one conversion question.", result: "Evidence-led iteration" }] },
  { slug: "businesses", label: "Businesses", eyebrow: "09 / Operating systems", summary: "Practical systems for businesses that need less friction between attention, delivery, and revenue.", accent: "green", projects: [{ title: "Local business growth system", description: "A focused mix of offer, follow-up, and delivery improvements.", result: "A clearer operating loop" }, { title: "Service offer reset", description: "Replaced generic services with a sharper revenue-leak promise.", result: "Value before volume" }, { title: "Client onboarding flow", description: "Reduced the handoff friction between signed deal and useful work.", result: "Faster first win" }] },
  { slug: "failed-projects", label: "Failed Projects", eyebrow: "10 / Post-mortems", summary: "The projects that did not work, preserved as evidence instead of hidden as embarrassment.", accent: "red", projects: [{ title: "The general dropship store", description: "A broad catalog, weak positioning, and expensive lessons.", result: "-$1,150 tuition" }, { title: "The perfect design system", description: "Three weeks of polish before the proposition was proven.", result: "Sell before polish" }, { title: "The faceless clip channel", description: "Views without buyer intent, audience, or durable trust.", result: "Vanity is not demand" }] },
  { slug: "other", label: "Other", eyebrow: "11 / The margins", summary: "Experiments that sit between disciplines and become useful because they connect them.", accent: "orange", projects: [{ title: "Research and field notes", description: "Questions that became experiments, conversations, and better briefs.", result: "Curiosity made concrete" }, { title: "Hybrid creative systems", description: "Combining image, code, and strategy into a single workflow.", result: "More useful intersections" }, { title: "The next unknown", description: "A place reserved for the work that has not found its label yet.", result: "Still in progress" }] },
];

export function getDiscipline(slug: string) {
  return disciplines.find((discipline) => discipline.slug === slug);
}
